# -*- mode: ruby -*-
VAGRANTFILE_API_VERSION = "2"


Vagrant::configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "windows98.box"
  config.vm.hostname = "windows"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "./", "C:\\"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1026
    v.cpus = 2
    v.gui = true
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine # :machine or :box
  end
end
