# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The '2' in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure('2') do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = 'ramsey/macos-mojave'
  # config.vm.box_check_update = false
  config.vm.network 'private_network', ip: '192.168.33.10'
  config.vm.provider 'virtualbox' do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.cpus = 2
    vb.memory = 4096

    vb.customize [
      "modifyvm", :id,
      "--cpuidset", "00000001", "000106e5", "00100800", "0098e3fd", "bfebfbff",
      "--firmware", "efi",
      "--vram", "128",
      "--clipboard", "bidirectional",
      "--draganddrop", "bidirectional",
      "--audio", "pulse",
      "--audiocontroller", "hda",
      "--audioin", "on",
      "--audioout", "on",
      "--graphicscontroller", "vboxsvga",
      "--accelerate3d", "on",
      "--usb", "on",
      "--usbxhci", "on",
      "--usbehci", "on"
    ]

    vb.customize ["storageattach", :id,
                  "--storagectl", "SATA Controller",
                  "--port", "1", "--device", "0",
                  "--type", "dvddrive",
                  "--medium", "emptydrive"]

    vb.customize [
      "setextradata", :id,
      "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct", "iMac14.2"
    ]
    vb.customize [
      "setextradata", :id,
      "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion", "1.0"
    ]
    vb.customize [
      "setextradata", :id,
      "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct", "iloveapple"
    ]
    vb.customize [
      "setextradata", :id,
      "VBoxInternal/Devices/smc/0/Config/DeviceKey", "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
    ]
    vb.customize [
      "setextradata", :id,
      "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC", 1
    ]
    vb.customize ['setextradata', :id, 'GUI/ScaleFactor', '1.00']
  end

  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vbguest.auto_update = false
  end
end
