# -*- mode: ruby -*-
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'Sliim/kali-2016.2-amd64'
  config.vm.hostname = 'kali'
  config.vm.network 'private_network', type: 'dhcp'
  config.vm.synced_folder './', '/vagrant', id: 'vagrant-kali'

  config.vm.provider 'virtualbox' do |v|
    v.customize ['modifyvm', :id, '--vram', '16']
    v.memory = 1048
    v.cpus = 1
    v.gui = true
  end

  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :machine # :machine or :box
  end
end
